customCommands:
  - key: "W"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        key: "BranchType"
        options:
          - value: "feat"
            name: "feature"
          - value: "fix"
            name: "hotfix/bugfix"
          - value: "docs"
            name: "document"
          - value: "refactor"
            name: "refactor"
      - type: "input"
        title: "Commit"
        key: "Commit"
        initialValue: ""
      - type: "input"
        title: "Description"
        key: "Desc"
        initialValue: ""
    command: "git commit -m '{{.Form.BranchType}}: ['$(git branch --show-current)'] {{.Form.Commit}}' -m '{{.Form.Desc}}' --no-verify"
    context: "global"
    subprocess: true
